# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gynacare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='annonid',
            new_name='myid',
        ),
    ]
